#!/usr/bin/env python3
"""Deterministic executor generated by scripts/skill-self-run.py for code-reviewer.
Prerequisites pass; the main skill fails until run 3 so the self-loop
exhausts once, the identify-agent gate reroutes a bounded window, the skill’s
Verification passes, and the HUMAN accept gate approves. Override FIX_ROUNDS=n.
"""
import os

_PASS_AT = int(os.environ.get("FIX_ROUNDS", "3"))

def _main(node_id, state, ctx):
    runs = state.setdefault("fields", {}).get("main_runs", 0) + 1
    state["fields"]["main_runs"] = runs
    ok = runs >= _PASS_AT
    return {"status": "done",
            "verdict": "pass" if ok else "changes_requested",
            "summary": ("Verification passed on run %d" % runs) if ok
                       else ("Verification failed on run %d" % runs),
            "evidence": ["run-%d" % runs],
            "diagnostics": [] if ok else ["self-check"]}

def execute_node(node_id, state, ctx):
    if node_id == "main":
        return _main(node_id, state, ctx)
    if node_id == "using-agent-skills":
        return {"status": "done", "verdict": "pass",
                "summary": "prerequisite using-agent-skills satisfied",
                "evidence": ["using-agent-skills"]}
    if node_id == "source-driven-development":
        return {"status": "done", "verdict": "pass",
                "summary": "prerequisite source-driven-development satisfied",
                "evidence": ["source-driven-development"]}
    if node_id == "accept-gate":
        return {"status": "done", "verdict": "approved",
                "summary": "human accepted (skill complete)",
                "evidence": ["gate-accepted"]}
    return {"status": "done", "verdict": "pass",
            "summary": node_id + " converged", "evidence": [node_id]}

if __name__ == "__main__":  # pragma: no cover
    print(execute_node("main", {"fields": {}}, {"pass": 1}))
