#!/usr/bin/env python3
"""Deterministic executor generated by scripts/goal-to-graph.py for booking-mvp.
verify fails until run 3, so the fix-verify loop exhausts once, the
identify-agent gate reroutes a bounded window, verification passes, and the HUMAN
release-gate gate approves once ready. Override with FIX_ROUNDS=<n> when running.
"""
import os

_PASS_AT = int(os.environ.get("FIX_ROUNDS", "3"))

def _verify(node_id, state, ctx):
    runs = state.setdefault("fields", {}).get("verify_runs", 0) + 1
    state["fields"]["verify_runs"] = runs
    ok = runs >= _PASS_AT
    return {"status": "done",
            "verdict": "pass" if ok else "changes_requested",
            "summary": ("verification green on run %d" % runs) if ok
                       else ("verification failed on run %d" % runs),
            "evidence": ["verify-%d" % runs],
            "diagnostics": [] if ok else ["regression"]}

def execute_node(node_id, state, ctx):
    if node_id == "verify":
        return _verify(node_id, state, ctx)
    if node_id == "spec":
        return {"status": "done", "verdict": "pass",
                "summary": "spec + acceptance criteria for the goal",
                "evidence": ["spec"]}
    if node_id == "build":
        return {"status": "done", "verdict": "pass",
                "summary": "deliverable implemented",
                "evidence": ["build-" + str(ctx.get("pass"))]}
    if node_id == "release-gate":
        return {"status": "done", "verdict": "approved",
                "summary": "human approved (goal complete)",
                "evidence": ["gate-release-gate"]}
    return {"status": "done", "verdict": "pass",
            "summary": node_id + " converged", "evidence": [node_id]}

if __name__ == "__main__":  # pragma: no cover
    print(execute_node("verify", {"fields": {}}, {"pass": 1}))
